use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;
use std::sync::Mutex;

use rusqlite::Connection;
use tauri::{AppHandle, Emitter};

use crate::services::config_manager::ConfigManager;

const USAGE_DB_FILE: &str = "usage.db";
const PENDING_DIR: &str = "usage-pending";
const HOOK_DIR: &str = "hooks";
const HOOK_SCRIPT_NAME_UNIX: &str = "claude-skill-usage.sh";
const HOOK_SCRIPT_NAME_WIN: &str = "claude-skill-usage.ps1";
const HOOK_MARKER: &str = "# skills-manager-usage-hook";
const LEGACY_LOG_FILE: &str = "usage-events.logl";

/// Bash 版 hook 脚本（macOS/Linux）
/// 每次调用生成独立文件，避免并发写入冲突
const HOOK_SCRIPT_UNIX: &str = r#"#!/bin/bash
# skills-manager-usage-hook
# Auto-generated by Skills Manager. Do not edit manually.
# Zero external dependencies: only bash + sed + tr (no jq required).
# Writes one file per event to avoid concurrent write conflicts.
input=$(cat)
[ -z "$input" ] && exit 0
ts=$(date +%s)
pid=$$
rand=$RANDOM
dir="$HOME/.skills-manager/usage-pending"
mkdir -p "$dir" 2>/dev/null
# Escape for JSON string embedding, collapse newlines
escaped=$(printf '%s' "$input" | sed 's/\\/\\\\/g; s/"/\\"/g' | tr '\n' ' ')
tmp="${dir}/.tmp-${ts}-${pid}-${rand}"
final="${dir}/${ts}-${pid}-${rand}.json"
echo "{\"raw\":\"$escaped\",\"tool_id\":\"claude-code\",\"ts\":$ts}" > "$tmp"
mv "$tmp" "$final"
"#;

/// PowerShell 版 hook 脚本（Windows）
const HOOK_SCRIPT_WIN: &str = r#"# skills-manager-usage-hook
# Auto-generated by Skills Manager. Do not edit manually.
# Writes one file per event to avoid concurrent write conflicts.
$input = [Console]::In.ReadToEnd()
if ([string]::IsNullOrEmpty($input)) { exit 0 }
$ts = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()
$procId = $PID
$rand = Get-Random -Maximum 999999
$dir = Join-Path $env:USERPROFILE ".skills-manager\usage-pending"
New-Item -ItemType Directory -Force -Path $dir | Out-Null
$escaped = $input -replace '\\', '\\' -replace '"', '\"' -replace "`r?`n", " "
$content = "{`"raw`":`"$escaped`",`"tool_id`":`"claude-code`",`"ts`":$ts}"
$final = Join-Path $dir "${ts}-${procId}-${rand}.json"
$tmp = Join-Path $dir ".tmp-${ts}-${procId}-${rand}"
[System.IO.File]::WriteAllText($tmp, $content)
Rename-Item -Path $tmp -Destination $final
"#;

#[derive(Debug, Deserialize)]
struct UsageEvent {
    raw: Option<String>,
    tool_id: String,
    ts: i64,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct SkillUsageStats {
    pub total: u64,
    pub by_tool: HashMap<String, u64>,
    pub last_called_at: Option<i64>,
}

fn skills_manager_dir() -> PathBuf {
    dirs::home_dir()
        .unwrap_or_default()
        .join(".skills-manager")
}

fn usage_db_path() -> PathBuf {
    skills_manager_dir().join(USAGE_DB_FILE)
}

fn pending_dir() -> PathBuf {
    skills_manager_dir().join(PENDING_DIR)
}

fn hook_script_path() -> PathBuf {
    let name = if cfg!(target_os = "windows") {
        HOOK_SCRIPT_NAME_WIN
    } else {
        HOOK_SCRIPT_NAME_UNIX
    };
    skills_manager_dir().join(HOOK_DIR).join(name)
}

fn hook_script_content() -> &'static str {
    if cfg!(target_os = "windows") {
        HOOK_SCRIPT_WIN
    } else {
        HOOK_SCRIPT_UNIX
    }
}

/// 建立数据库连接并初始化表
fn open_db() -> Result<Connection, String> {
    let db_path = usage_db_path();
    if let Some(parent) = db_path.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("Failed to create db dir: {}", e))?;
    }
    let conn = Connection::open(&db_path)
        .map_err(|e| format!("Failed to open usage db: {}", e))?;
    conn.execute_batch(
        "CREATE TABLE IF NOT EXISTS usage_events (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            skill_id TEXT NOT NULL,
            tool_id TEXT NOT NULL,
            event_type TEXT NOT NULL,
            ts INTEGER NOT NULL
        );
        CREATE INDEX IF NOT EXISTS idx_usage_skill ON usage_events(skill_id);
        CREATE INDEX IF NOT EXISTS idx_usage_tool ON usage_events(tool_id);
        CREATE INDEX IF NOT EXISTS idx_usage_ts ON usage_events(ts);",
    )
    .map_err(|e| format!("Failed to init usage table: {}", e))?;
    Ok(conn)
}

/// Extract skill identifier from a hook event.
fn extract_skill_id(event: &UsageEvent) -> Option<String> {
    let raw = event.raw.as_ref()?;
    let raw_value: serde_json::Value = serde_json::from_str(raw).ok()?;
    let hook_event = raw_value.get("hook_event_name").and_then(|v| v.as_str())?;

    match hook_event {
        "PostToolUse" => {
            let tool_input = raw_value.get("tool_input")?;
            extract_skill_id_from_value(tool_input)
        }
        "UserPromptSubmit" => {
            let prompt = raw_value.get("prompt").and_then(|v| v.as_str())?;
            extract_skill_from_slash_command(prompt)
        }
        _ => None,
    }
}

fn extract_skill_from_slash_command(prompt: &str) -> Option<String> {
    let trimmed = prompt.trim();
    if !trimmed.starts_with('/') {
        return None;
    }
    let after_slash = &trimmed[1..];
    let end = after_slash
        .find(|c: char| !c.is_alphanumeric() && c != '-' && c != '_')
        .unwrap_or(after_slash.len());
    if end == 0 {
        return None;
    }
    let skill_name = &after_slash[..end];
    if skill_name.is_empty() {
        return None;
    }
    let builtins = [
        "help", "clear", "compact", "config", "cost", "doctor", "exit", "init",
        "login", "logout", "memory", "model", "permissions", "review", "status",
        "terminal-setup", "vim", "bug", "resume", "release-notes", "feedback",
        "mcp", "usage",
    ];
    if builtins.contains(&skill_name) {
        return None;
    }
    Some(skill_name.to_string())
}

fn extract_skill_id_from_value(tool_input: &serde_json::Value) -> Option<String> {
    let obj = tool_input.as_object()?;
    for key in ["skill_id", "skill_name", "name", "skill"] {
        if let Some(val) = obj.get(key) {
            if let Some(s) = val.as_str() {
                if !s.is_empty() {
                    return Some(s.to_string());
                }
            }
        }
    }
    None
}

/// 获取 hook 事件的类型字符串
fn get_event_type(event: &UsageEvent) -> String {
    if let Some(raw) = &event.raw {
        if let Ok(v) = serde_json::from_str::<serde_json::Value>(raw) {
            if let Some(name) = v.get("hook_event_name").and_then(|s| s.as_str()) {
                return name.to_string();
            }
        }
    }
    "Unknown".to_string()
}

/// 解析一个 pending 文件并写入 SQLite
fn import_pending_file(conn: &Connection, file_path: &PathBuf) -> Result<bool, String> {
    let content = fs::read_to_string(file_path)
        .map_err(|e| format!("Failed to read pending file: {}", e))?;
    let trimmed = content.trim();
    if trimmed.is_empty() {
        return Ok(false);
    }
    let event: UsageEvent = match serde_json::from_str(trimmed) {
        Ok(e) => e,
        Err(_) => return Ok(false),
    };
    let skill_id = match extract_skill_id(&event) {
        Some(id) => id,
        None => return Ok(false),
    };
    let event_type = get_event_type(&event);
    conn.execute(
        "INSERT INTO usage_events (skill_id, tool_id, event_type, ts) VALUES (?1, ?2, ?3, ?4)",
        rusqlite::params![skill_id, event.tool_id, event_type, event.ts],
    )
    .map_err(|e| format!("Failed to insert usage event: {}", e))?;
    Ok(true)
}

/// 扫描 pending 目录，导入所有文件到 SQLite，导入后删除
pub fn import_pending_events(conn: &Connection) -> Result<usize, String> {
    let dir = pending_dir();
    if !dir.exists() {
        return Ok(0);
    }
    let entries = fs::read_dir(&dir)
        .map_err(|e| format!("Failed to read pending dir: {}", e))?;
    let mut count = 0;
    for entry in entries.flatten() {
        let path = entry.path();
        // 只处理 .json 文件，跳过 .tmp- 前缀的临时文件
        let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
        if !name.ends_with(".json") || name.starts_with(".tmp-") {
            continue;
        }
        match import_pending_file(conn, &path) {
            Ok(true) => {
                count += 1;
                let _ = fs::remove_file(&path);
            }
            Ok(false) => {
                // 解析失败或无 skill_id，删除避免累积
                let _ = fs::remove_file(&path);
            }
            Err(_) => {
                // 导入出错，保留文件等待下次重试
            }
        }
    }
    Ok(count)
}

/// 迁移旧 logl 文件到 SQLite（一次性）
fn migrate_legacy_log(conn: &Connection) -> Result<usize, String> {
    let log_path = skills_manager_dir().join(LEGACY_LOG_FILE);
    if !log_path.exists() {
        return Ok(0);
    }
    let content = fs::read_to_string(&log_path)
        .map_err(|e| format!("Failed to read legacy log: {}", e))?;
    let mut count = 0;
    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        let event: UsageEvent = match serde_json::from_str(line) {
            Ok(e) => e,
            Err(_) => continue,
        };
        let skill_id = match extract_skill_id(&event) {
            Some(id) => id,
            None => continue,
        };
        let event_type = get_event_type(&event);
        let _ = conn.execute(
            "INSERT INTO usage_events (skill_id, tool_id, event_type, ts) VALUES (?1, ?2, ?3, ?4)",
            rusqlite::params![skill_id, event.tool_id, event_type, event.ts],
        );
        count += 1;
    }
    // 迁移成功后删除旧 logl
    let _ = fs::remove_file(&log_path);
    Ok(count)
}

#[tauri::command]
pub fn get_skill_usage_stats() -> Result<HashMap<String, SkillUsageStats>, String> {
    let conn = open_db()?;
    // 先导入 pending 文件
    let _ = import_pending_events(&conn);

    let mut stmt = conn
        .prepare("SELECT skill_id, tool_id, COUNT(*) as cnt, MAX(ts) as last_ts FROM usage_events GROUP BY skill_id, tool_id")
        .map_err(|e| format!("Failed to prepare query: {}", e))?;

    let mut stats: HashMap<String, SkillUsageStats> = HashMap::new();
    let rows = stmt
        .query_map([], |row| {
            Ok((
                row.get::<_, String>(0)?,
                row.get::<_, String>(1)?,
                row.get::<_, u64>(2)?,
                row.get::<_, Option<i64>>(3)?,
            ))
        })
        .map_err(|e| format!("Failed to query usage: {}", e))?;

    for row in rows.flatten() {
        let (skill_id, tool_id, cnt, last_ts) = row;
        let entry = stats.entry(skill_id).or_default();
        entry.total += cnt;
        entry.by_tool.insert(tool_id, cnt);
        if let Some(ts) = last_ts {
            if ts > entry.last_called_at.unwrap_or(0) {
                entry.last_called_at = Some(ts);
            }
        }
    }
    Ok(stats)
}

#[tauri::command]
pub fn clear_usage_stats() -> Result<(), String> {
    let conn = open_db()?;
    conn.execute("DELETE FROM usage_events", [])
        .map_err(|e| format!("Failed to clear usage events: {}", e))?;
    // 清空 pending 目录
    let dir = pending_dir();
    if dir.exists() {
        if let Ok(entries) = fs::read_dir(&dir) {
            for entry in entries.flatten() {
                let _ = fs::remove_file(entry.path());
            }
        }
    }
    Ok(())
}

#[tauri::command]
pub fn get_usage_hook_status() -> Result<bool, String> {
    Ok(is_hook_installed())
}

fn claude_settings_path() -> PathBuf {
    dirs::home_dir()
        .unwrap_or_default()
        .join(".claude")
        .join("settings.json")
}

/// 生成 hook 命令字符串
fn build_hook_command() -> String {
    let script_path = hook_script_path();
    if cfg!(target_os = "windows") {
        // Windows: PowerShell
        format!(
            "powershell -ExecutionPolicy Bypass -File \"{}\"",
            script_path.to_string_lossy()
        )
    } else {
        // Unix: bash
        format!("bash \"{}\"", script_path.to_string_lossy())
    }
}

fn find_sm_hook_entry_in(settings: &serde_json::Value, event_key: &str) -> Option<usize> {
    let hooks = settings.get("hooks")?;
    let event_arr = hooks.get(event_key)?;
    let arr = event_arr.as_array()?;
    for (i, entry) in arr.iter().enumerate() {
        if event_key == "PostToolUse" {
            let matcher = entry.get("matcher").and_then(|m| m.as_str()).unwrap_or("");
            if matcher != "Skill" {
                continue;
            }
        }
        let hook_list = entry.get("hooks").and_then(|h| h.as_array());
        if let Some(hooks) = hook_list {
            for h in hooks {
                let cmd = h.get("command").and_then(|c| c.as_str()).unwrap_or("");
                if cmd.contains(HOOK_MARKER)
                    || cmd.contains("claude-skill-usage.sh")
                    || cmd.contains("claude-skill-usage.ps1")
                {
                    return Some(i);
                }
            }
        }
    }
    None
}

fn is_hook_installed() -> bool {
    let settings_path = claude_settings_path();
    let content = match fs::read_to_string(&settings_path) {
        Ok(c) => c,
        Err(_) => return false,
    };
    let settings: serde_json::Value = match serde_json::from_str(&content) {
        Ok(v) => v,
        Err(_) => return false,
    };
    find_sm_hook_entry_in(&settings, "PostToolUse").is_some()
        || find_sm_hook_entry_in(&settings, "UserPromptSubmit").is_some()
}

#[tauri::command]
pub fn install_usage_hook() -> Result<(), String> {
    // 1. Write hook script
    let hook_dir = skills_manager_dir().join(HOOK_DIR);
    fs::create_dir_all(&hook_dir).map_err(|e| format!("Failed to create hook dir: {}", e))?;
    let script_path = hook_script_path();
    fs::write(&script_path, hook_script_content())
        .map_err(|e| format!("Failed to write hook script: {}", e))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let perms = fs::Permissions::from_mode(0o755);
        fs::set_permissions(&script_path, perms)
            .map_err(|e| format!("Failed to set hook script permissions: {}", e))?;
    }

    // 2. Create pending directory
    fs::create_dir_all(pending_dir())
        .map_err(|e| format!("Failed to create pending dir: {}", e))?;

    // 3. Inject into Claude Code settings.json
    let settings_path = claude_settings_path();
    if let Some(parent) = settings_path.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("Failed to create .claude dir: {}", e))?;
    }

    let content = fs::read_to_string(&settings_path).unwrap_or_else(|_| "{}".to_string());
    let mut settings: serde_json::Value = serde_json::from_str(&content)
        .map_err(|e| format!("Failed to parse Claude settings.json: {}", e))?;

    let hook_command = build_hook_command();

    if settings.get("hooks").is_none() {
        settings["hooks"] = serde_json::json!({});
    }

    // PostToolUse: matcher "Skill"
    remove_sm_entries(&mut settings, "PostToolUse");
    if settings["hooks"].get("PostToolUse").is_none() {
        settings["hooks"]["PostToolUse"] = serde_json::json!([]);
    }
    let post_entry = serde_json::json!({
        "matcher": "Skill",
        "hooks": [{
            "type": "command",
            "command": hook_command
        }]
    });
    settings["hooks"]["PostToolUse"]
        .as_array_mut()
        .expect("PostToolUse should be array")
        .push(post_entry);

    // UserPromptSubmit: no matcher
    remove_sm_entries(&mut settings, "UserPromptSubmit");
    if settings["hooks"].get("UserPromptSubmit").is_none() {
        settings["hooks"]["UserPromptSubmit"] = serde_json::json!([]);
    }
    let submit_entry = serde_json::json!({
        "hooks": [{
            "type": "command",
            "command": hook_command
        }]
    });
    settings["hooks"]["UserPromptSubmit"]
        .as_array_mut()
        .expect("UserPromptSubmit should be array")
        .push(submit_entry);

    let output = serde_json::to_string_pretty(&settings)
        .map_err(|e| format!("Failed to serialize settings: {}", e))?;
    fs::write(&settings_path, output)
        .map_err(|e| format!("Failed to write Claude settings.json: {}", e))?;

    Ok(())
}

fn remove_sm_entries(settings: &mut serde_json::Value, event_key: &str) {
    while let Some(idx) = find_sm_hook_entry_in(settings, event_key) {
        if let Some(arr) = settings
            .get_mut("hooks")
            .and_then(|h| h.get_mut(event_key))
            .and_then(|p| p.as_array_mut())
        {
            arr.remove(idx);
        } else {
            break;
        }
    }
}

#[tauri::command]
pub fn uninstall_usage_hook() -> Result<(), String> {
    let settings_path = claude_settings_path();
    let content = fs::read_to_string(&settings_path).unwrap_or_else(|_| "{}".to_string());
    let mut settings: serde_json::Value = serde_json::from_str(&content)
        .map_err(|e| format!("Failed to parse Claude settings.json: {}", e))?;

    remove_sm_entries(&mut settings, "PostToolUse");
    remove_sm_entries(&mut settings, "UserPromptSubmit");

    let output = serde_json::to_string_pretty(&settings)
        .map_err(|e| format!("Failed to serialize settings: {}", e))?;
    fs::write(&settings_path, output)
        .map_err(|e| format!("Failed to write Claude settings.json: {}", e))?;

    Ok(())
}

/// Ensure hook state matches the preference. Called on app startup.
/// Always rewrites the hook script to the latest version (handles upgrades).
pub fn sync_usage_hook_with_config() {
    let manager = ConfigManager::new();
    let config = match manager.load() {
        Ok(c) => c,
        Err(_) => return,
    };
    let enabled = config
        .preferences
        .map(|p| p.skill_usage_monitor)
        .unwrap_or(true);

    let installed = is_hook_installed();
    if enabled && !installed {
        let _ = install_usage_hook();
    } else if !enabled && installed {
        let _ = uninstall_usage_hook();
    } else if enabled && installed {
        // Hook already installed: still rewrite script to ensure latest version
        let hook_dir = skills_manager_dir().join(HOOK_DIR);
        let _ = fs::create_dir_all(&hook_dir);
        let script_path = hook_script_path();
        let _ = fs::write(&script_path, hook_script_content());
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let _ = fs::set_permissions(&script_path, fs::Permissions::from_mode(0o755));
        }
        let _ = fs::create_dir_all(pending_dir());
        // Also update command in settings.json if platform changed
        let settings_path = claude_settings_path();
        if let Ok(content) = fs::read_to_string(&settings_path) {
            if let Ok(mut settings) = serde_json::from_str::<serde_json::Value>(&content) {
                let expected_cmd = build_hook_command();
                let needs_update = ["PostToolUse", "UserPromptSubmit"].iter().any(|key| {
                    if let Some(arr) = settings.get("hooks").and_then(|h| h.get(key)).and_then(|a| a.as_array()) {
                        arr.iter().any(|entry| {
                            if let Some(hooks) = entry.get("hooks").and_then(|h| h.as_array()) {
                                hooks.iter().any(|h| {
                                    let cmd = h.get("command").and_then(|c| c.as_str()).unwrap_or("");
                                    cmd.contains(HOOK_MARKER) && cmd != expected_cmd
                                })
                            } else {
                                false
                            }
                        })
                    } else {
                        false
                    }
                });
                if needs_update {
                    remove_sm_entries(&mut settings, "PostToolUse");
                    remove_sm_entries(&mut settings, "UserPromptSubmit");
                    // Re-add entries with the correct command
                    if settings.get("hooks").is_none() {
                        settings["hooks"] = serde_json::json!({});
                    }
                    if settings["hooks"].get("PostToolUse").is_none() {
                        settings["hooks"]["PostToolUse"] = serde_json::json!([]);
                    }
                    settings["hooks"]["PostToolUse"].as_array_mut().unwrap().push(serde_json::json!({
                        "matcher": "Skill",
                        "hooks": [{"type": "command", "command": expected_cmd.clone()}]
                    }));
                    if settings["hooks"].get("UserPromptSubmit").is_none() {
                        settings["hooks"]["UserPromptSubmit"] = serde_json::json!([]);
                    }
                    settings["hooks"]["UserPromptSubmit"].as_array_mut().unwrap().push(serde_json::json!({
                        "hooks": [{"type": "command", "command": expected_cmd}]
                    }));
                    let _ = fs::write(&settings_path, serde_json::to_string_pretty(&settings).unwrap_or_default());
                }
            }
        }
    }
}

// ===== 文件监听 + 自动导入 =====

/// 文件监听器，用于在 lib.rs setup 中启动
static WATCHER_INITIALIZED: Mutex<bool> = Mutex::new(false);

/// 启动 pending 目录监听，新文件到达时导入到 SQLite 并 emit event
pub fn start_usage_watcher(app: AppHandle) {
    let mut guard = WATCHER_INITIALIZED.lock().unwrap_or_else(|e| e.into_inner());
    if *guard {
        return;
    }
    *guard = true;
    drop(guard);

    // 确保目录存在
    let _ = fs::create_dir_all(pending_dir());

    // 启动时先迁移旧 logl + 导入现有 pending
    std::thread::spawn(move || {
        if let Ok(conn) = open_db() {
            let _ = migrate_legacy_log(&conn);
            let _ = import_pending_events(&conn);
            // 迁移后通知前端刷新
            let _ = app.emit("usage-stats-updated", ());
        }

        // 启动 notify 监听
        use notify::{Watcher, RecursiveMode, RecommendedWatcher, EventKind, Config};

        let pending = pending_dir();
        let app_clone = app.clone();
        let mut watcher: RecommendedWatcher = match Watcher::new(
            move |res: notify::Result<notify::Event>| {
                if let Ok(event) = res {
                    let should_import = matches!(
                        event.kind,
                        EventKind::Create(_) | EventKind::Modify(_)
                    );
                    if !should_import {
                        return;
                    }
                    std::thread::sleep(std::time::Duration::from_millis(200));
                    if let Ok(conn) = open_db() {
                        let _ = import_pending_events(&conn);
                        let _ = app_clone.emit("usage-stats-updated", ());
                    }
                }
            },
            Config::default(),
        ) {
            Ok(w) => w,
            Err(_) => return,
        };

        let _ = watcher.watch(&pending, RecursiveMode::NonRecursive);

        // 保持线程存活
        loop {
            std::thread::sleep(std::time::Duration::from_secs(60));
        }
    });
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use std::path::Path;

    static HOME_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

    fn with_temp_home<F: FnOnce(&Path)>(f: F) {
        let _guard = HOME_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let tmp = std::env::temp_dir().join(format!(
            "sm-test-{}-{}",
            std::process::id(),
            std::time::SystemTime::now().elapsed().unwrap().as_nanos()
        ));
        let _ = fs::create_dir_all(&tmp);
        let old_home = std::env::var("HOME").ok();
        std::env::set_var("HOME", &tmp);
        let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| f(&tmp)));
        if let Some(old) = old_home {
            std::env::set_var("HOME", old);
        } else {
            std::env::remove_var("HOME");
        }
        let _ = fs::remove_dir_all(&tmp);
        if let Err(payload) = result {
            std::panic::resume_unwind(payload);
        }
    }

    /// 写入一个 pending 事件文件
    fn write_pending_event(home: &Path, raw_json: &str, tool_id: &str, ts: i64) -> PathBuf {
        let dir = home.join(".skills-manager").join(PENDING_DIR);
        fs::create_dir_all(&dir).unwrap();
        let escaped = raw_json.replace('\\', "\\\\").replace('"', "\\\"");
        let content = format!(
            r#"{{"raw":"{}","tool_id":"{}","ts":{}}}"#,
            escaped, tool_id, ts
        );
        let path = dir.join(format!("{}-1-1.json", ts));
        fs::write(&path, content).unwrap();
        path
    }

    #[test]
    fn extract_skill_id_tries_known_field_names() {
        let cases = [
            (r#"{"hook_event_name":"PostToolUse","tool_input":{"skill_id":"abc"}}"#, Some("abc")),
            (r#"{"hook_event_name":"PostToolUse","tool_input":{"skill_name":"xyz"}}"#, Some("xyz")),
            (r#"{"hook_event_name":"PostToolUse","tool_input":{"name":"foo"}}"#, Some("foo")),
            (r#"{"hook_event_name":"PostToolUse","tool_input":{"skill":"bar"}}"#, Some("bar")),
            (r#"{"hook_event_name":"PostToolUse","tool_input":{"other":"val"}}"#, None),
            (r#"{"hook_event_name":"PostToolUse","tool_input":{"skill_id":""}}"#, None),
            (r#"{}"#, None),
        ];
        for (raw_json, expected) in cases {
            let event = UsageEvent {
                raw: Some(raw_json.to_string()),
                tool_id: "claude-code".to_string(),
                ts: 0,
            };
            let got = extract_skill_id(&event);
            assert_eq!(got.as_deref(), expected, "failed for raw: {}", raw_json);
        }
    }

    #[test]
    fn extract_skill_id_from_slash_command() {
        let cases = [
            (r#"{"hook_event_name":"UserPromptSubmit","prompt":"/ab-testing 测试按钮"}"#, Some("ab-testing")),
            (r#"{"hook_event_name":"UserPromptSubmit","prompt":"/pdf"}"#, Some("pdf")),
            (r#"{"hook_event_name":"UserPromptSubmit","prompt":"请帮我设计实验"}"#, None),
            (r#"{"hook_event_name":"UserPromptSubmit","prompt":"/help"}"#, None),
            (r#"{"hook_event_name":"UserPromptSubmit","prompt":"/clear"}"#, None),
            (r#"{"hook_event_name":"UserPromptSubmit","prompt":""}"#, None),
        ];
        for (raw_json, expected) in cases {
            let event = UsageEvent {
                raw: Some(raw_json.to_string()),
                tool_id: "claude-code".to_string(),
                ts: 0,
            };
            let got = extract_skill_id(&event);
            assert_eq!(got.as_deref(), expected, "failed for raw: {}", raw_json);
        }
    }

    #[test]
    fn get_skill_usage_stats_aggregates_by_skill_and_tool() {
        with_temp_home(|home| {
            let stdin1 = r#"{"hook_event_name":"PostToolUse","tool_name":"Skill","tool_input":{"skill_id":"alpha"}}"#;
            let stdin2 = r#"{"hook_event_name":"PostToolUse","tool_name":"Skill","tool_input":{"skill_id":"alpha"}}"#;
            let stdin3 = r#"{"hook_event_name":"UserPromptSubmit","prompt":"/beta 测试"}"#;

            write_pending_event(home, stdin1, "claude-code", 100);
            write_pending_event(home, stdin2, "claude-code", 101);
            write_pending_event(home, stdin3, "claude-code", 102);

            let stats = get_skill_usage_stats().expect("should parse");
            let alpha = stats.get("alpha").expect("alpha stats");
            assert_eq!(alpha.total, 2);
            assert_eq!(alpha.by_tool.get("claude-code"), Some(&2));

            let beta = stats.get("beta").expect("beta stats");
            assert_eq!(beta.total, 1);
            assert_eq!(beta.by_tool.get("claude-code"), Some(&1));

            assert_eq!(stats.len(), 2, "only alpha and beta should be counted");
        });
    }

    #[test]
    fn get_skill_usage_stats_returns_empty_when_no_events() {
        with_temp_home(|_home| {
            let stats = get_skill_usage_stats().expect("should succeed with empty result");
            assert!(stats.is_empty());
        });
    }

    #[test]
    fn clear_usage_stats_removes_all_events() {
        with_temp_home(|home| {
            write_pending_event(
                home,
                r#"{"hook_event_name":"PostToolUse","tool_input":{"skill":"abc"}}"#,
                "claude-code",
                100,
            );
            // 触发导入
            let _ = get_skill_usage_stats();
            // 清空
            clear_usage_stats().expect("clear should succeed");
            // 再查
            let stats = get_skill_usage_stats().expect("should succeed");
            assert!(stats.is_empty(), "stats should be empty after clear");
        });
    }

    #[test]
    fn find_sm_hook_entry_detects_installed_hook() {
        let settings: serde_json::Value = serde_json::json!({
            "hooks": {
                "PostToolUse": [
                    {
                        "matcher": "Skill",
                        "hooks": [{
                            "type": "command",
                            "command": "bash \"/Users/x/.skills-manager/hooks/claude-skill-usage.sh\""
                        }]
                    }
                ],
                "UserPromptSubmit": [
                    {
                        "hooks": [{
                            "type": "command",
                            "command": "bash \"/Users/x/.skills-manager/hooks/claude-skill-usage.sh\""
                        }]
                    }
                ]
            }
        });
        assert_eq!(find_sm_hook_entry_in(&settings, "PostToolUse"), Some(0));
        assert_eq!(find_sm_hook_entry_in(&settings, "UserPromptSubmit"), Some(0));
    }

    #[test]
    fn find_sm_hook_entry_ignores_non_sm_hooks() {
        let settings: serde_json::Value = serde_json::json!({
            "hooks": {
                "PostToolUse": [
                    {
                        "matcher": "Skill",
                        "hooks": [{
                            "type": "command",
                            "command": "some-other-script.sh"
                        }]
                    }
                ]
            }
        });
        assert_eq!(find_sm_hook_entry_in(&settings, "PostToolUse"), None);
    }

    #[test]
    fn install_and_uninstall_hook_preserves_other_settings() {
        with_temp_home(|home| {
            let claude_dir = home.join(".claude");
            fs::create_dir_all(&claude_dir).unwrap();
            let settings_path = claude_dir.join("settings.json");
            let original = serde_json::json!({
                "model": "kimi-k2",
                "hooks": {
                    "Notification": [{
                        "matcher": "Notification",
                        "hooks": [{"type": "command", "command": "afplay /x.mp3"}]
                    }],
                    "PostToolUse": [{
                        "matcher": "Bash",
                        "hooks": [{"type": "command", "command": "other-script.sh"}]
                    }]
                },
                "permissions": {"defaultMode": "bypassPermissions"}
            });
            fs::write(&settings_path, serde_json::to_string_pretty(&original).unwrap()).unwrap();

            install_usage_hook().expect("install should succeed");

            let after_install: serde_json::Value =
                serde_json::from_str(&fs::read_to_string(&settings_path).unwrap()).unwrap();

            assert_eq!(after_install.get("model").and_then(|m| m.as_str()), Some("kimi-k2"));
            assert_eq!(
                after_install.get("permissions").and_then(|p| p.get("defaultMode")).and_then(|m| m.as_str()),
                Some("bypassPermissions")
            );
            let post = after_install.get("hooks").and_then(|h| h.get("PostToolUse")).unwrap();
            let arr = post.as_array().unwrap();
            assert_eq!(arr.len(), 2, "should have Bash + Skill entries");
            let skill_entry = arr.iter().find(|e| e.get("matcher").and_then(|m| m.as_str()) == Some("Skill"));
            assert!(skill_entry.is_some(), "Skill matcher entry should be added");
            let notif = after_install.get("hooks").and_then(|h| h.get("Notification")).unwrap();
            assert_eq!(notif.as_array().unwrap().len(), 1);

            let script_path = home.join(".skills-manager").join("hooks").join(HOOK_SCRIPT_NAME_UNIX);
            assert!(script_path.exists(), "hook script should exist");
            #[cfg(unix)]
            {
                use std::os::unix::fs::PermissionsExt;
                let perms = fs::metadata(&script_path).unwrap().permissions().mode();
                assert_eq!(perms & 0o111, 0o111, "script should be executable");
            }

            assert_eq!(get_usage_hook_status().unwrap(), true);

            uninstall_usage_hook().expect("uninstall should succeed");
            let after_uninstall: serde_json::Value =
                serde_json::from_str(&fs::read_to_string(&settings_path).unwrap()).unwrap();
            let post = after_uninstall.get("hooks").and_then(|h| h.get("PostToolUse")).unwrap();
            let arr = post.as_array().unwrap();
            assert_eq!(arr.len(), 1, "only Bash entry should remain");
            assert_eq!(
                arr[0].get("matcher").and_then(|m| m.as_str()),
                Some("Bash"),
                "remaining entry should be Bash, not Skill"
            );
            assert_eq!(after_uninstall.get("model").and_then(|m| m.as_str()), Some("kimi-k2"));
            assert!(after_uninstall.get("hooks").and_then(|h| h.get("Notification")).is_some());

            assert_eq!(get_usage_hook_status().unwrap(), false);
        });
    }

    #[test]
    fn install_hook_is_idempotent() {
        with_temp_home(|home| {
            let claude_dir = home.join(".claude");
            fs::create_dir_all(&claude_dir).unwrap();
            fs::write(claude_dir.join("settings.json"), "{}").unwrap();

            install_usage_hook().expect("first install");
            install_usage_hook().expect("second install should not duplicate");

            let settings: serde_json::Value = serde_json::from_str(
                &fs::read_to_string(claude_dir.join("settings.json")).unwrap(),
            )
            .unwrap();
            let post = settings.get("hooks").unwrap().get("PostToolUse").unwrap();
            let arr = post.as_array().unwrap();
            assert_eq!(arr.len(), 1, "should have exactly one Skill entry, not duplicated");
        });
    }

    #[test]
    fn parse_real_claude_code_hook_output() {
        let real_raw = r#"{"session_id":"1fba2762","hook_event_name":"PostToolUse","tool_name":"Skill","tool_input":{"skill":"ab-testing"},"tool_response":{"success":true,"commandName":"ab-testing"},"tool_use_id":"functions.Skill:0","duration_ms":3}"#;
        with_temp_home(|home| {
            write_pending_event(home, real_raw, "claude-code", 1783836828);

            let stats = get_skill_usage_stats().expect("should parse");
            assert_eq!(stats.len(), 1, "should have exactly one skill entry");
            let entry = stats.get("ab-testing").expect("should find ab-testing skill");
            assert_eq!(entry.total, 1);
            assert_eq!(entry.by_tool.get("claude-code"), Some(&1));
            assert_eq!(entry.last_called_at, Some(1783836828));
        });
    }

    #[test]
    fn parse_real_slash_command_hook_output() {
        let stdin = r#"{"session_id":"abc","hook_event_name":"UserPromptSubmit","prompt":"/ab-testing 测试按钮颜色"}"#;
        with_temp_home(|home| {
            write_pending_event(home, stdin, "claude-code", 1783838000);

            let stats = get_skill_usage_stats().expect("should parse");
            assert_eq!(stats.len(), 1, "should have exactly one skill entry");
            let entry = stats.get("ab-testing").expect("should find ab-testing skill");
            assert_eq!(entry.total, 1);
            assert_eq!(entry.by_tool.get("claude-code"), Some(&1));
        });
    }

    #[test]
    fn migrate_legacy_log_imports_old_events() {
        with_temp_home(|home| {
            // 创建旧 logl 文件
            let sm_dir = home.join(".skills-manager");
            fs::create_dir_all(&sm_dir).unwrap();
            let log_path = sm_dir.join(LEGACY_LOG_FILE);
            let stdin = r#"{"hook_event_name":"PostToolUse","tool_input":{"skill":"migrated"}}"#;
            let escaped = stdin.replace('\\', "\\\\").replace('"', "\\\"");
            let line = format!(
                r#"{{"raw":"{}","tool_id":"claude-code","ts":1000}}"#,
                escaped
            );
            fs::write(&log_path, line).unwrap();

            // 迁移
            let conn = open_db().unwrap();
            let count = migrate_legacy_log(&conn).unwrap();
            assert_eq!(count, 1);
            assert!(!log_path.exists(), "legacy logl should be deleted after migration");

            // 查询
            let stats = get_skill_usage_stats().unwrap();
            assert_eq!(stats.get("migrated").unwrap().total, 1);
        });
    }
}
