use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DetectedEditor {
    pub id: String,
    pub name: String,
    pub command: String,
    pub available: bool,
    pub icon: String,
}

pub struct EditorDefinition {
    pub id: &'static str,
    pub name: &'static str,
    pub detect_cmd: &'static str,
    pub app_name: &'static str,  // macOS app name for detection
    pub open_cmd: &'static str,
    pub icon: &'static str,
    pub always_available: bool,
}

pub const EDITOR_DEFINITIONS: &[EditorDefinition] = &[
    EditorDefinition {
        id: "vscode",
        name: "VS Code",
        detect_cmd: "code",
        app_name: "Visual Studio Code",
        open_cmd: "code",
        icon: "vscode",
        always_available: false,
    },
    EditorDefinition {
        id: "cursor",
        name: "Cursor",
        detect_cmd: "cursor",
        app_name: "Cursor",
        open_cmd: "open -a Cursor",
        icon: "cursor",
        always_available: false,
    },
    EditorDefinition {
        id: "windsurf",
        name: "Windsurf",
        detect_cmd: "windsurf",
        app_name: "Windsurf",
        open_cmd: "open -a Windsurf",
        icon: "windsurf",
        always_available: false,
    },
    EditorDefinition {
        id: "antigravity",
        name: "Antigravity",
        detect_cmd: "",
        app_name: "Antigravity",
        open_cmd: "open -a Antigravity",
        icon: "antigravity",
        always_available: false,
    },
    EditorDefinition {
        id: "zed",
        name: "Zed",
        detect_cmd: "zed",
        app_name: "Zed",
        open_cmd: "zed",
        icon: "zed",
        always_available: false,
    },
    EditorDefinition {
        id: "sublime",
        name: "Sublime Text",
        detect_cmd: "subl",
        app_name: "Sublime Text",
        open_cmd: "subl",
        icon: "sublime",
        always_available: false,
    },
    EditorDefinition {
        id: "idea",
        name: "IntelliJ IDEA",
        detect_cmd: "idea",
        app_name: "IntelliJ IDEA",
        open_cmd: "idea",
        icon: "idea",
        always_available: false,
    },
    EditorDefinition {
        id: "pycharm",
        name: "PyCharm",
        detect_cmd: "pycharm",
        app_name: "PyCharm",
        open_cmd: "pycharm",
        icon: "pycharm",
        always_available: false,
    },
    EditorDefinition {
        id: "webstorm",
        name: "WebStorm",
        detect_cmd: "webstorm",
        app_name: "WebStorm",
        open_cmd: "webstorm",
        icon: "webstorm",
        always_available: false,
    },
    EditorDefinition {
        id: "xcode",
        name: "Xcode",
        detect_cmd: "xcode-select",
        app_name: "Xcode",
        open_cmd: "open -a Xcode",
        icon: "xcode",
        always_available: false,
    },
    EditorDefinition {
        id: "android-studio",
        name: "Android Studio",
        detect_cmd: "studio",
        app_name: "Android Studio",
        open_cmd: "open -a 'Android Studio'",
        icon: "android-studio",
        always_available: false,
    },
    EditorDefinition {
        id: "terminal",
        name: "Terminal",
        detect_cmd: "",
        app_name: "",
        open_cmd: "open -a Terminal",
        icon: "terminal",
        always_available: true,
    },
    EditorDefinition {
        id: "finder",
        name: "Finder",
        detect_cmd: "",
        app_name: "",
        open_cmd: "open",
        icon: "finder",
        always_available: true,
    },
    EditorDefinition {
        id: "builtin",
        name: "Built-in Editor",
        detect_cmd: "",
        app_name: "",
        open_cmd: "",
        icon: "builtin",
        always_available: true,
    },
];
