use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DetectedEditor {
    pub id: String,
    pub name: String,
    pub command: String,
    pub available: bool,
    pub icon: String,
}

pub struct EditorDefinition {
    pub id: &'static str,
    pub name: &'static str,
    pub detect_cmd: &'static str,
    pub open_cmd: &'static str,
    pub icon: &'static str,
    pub always_available: bool,
}

pub const EDITOR_DEFINITIONS: &[EditorDefinition] = &[
    EditorDefinition {
        id: "vscode",
        name: "VS Code",
        detect_cmd: "code",
        open_cmd: "code",
        icon: "vscode.svg",
        always_available: false,
    },
    EditorDefinition {
        id: "cursor",
        name: "Cursor",
        detect_cmd: "cursor",
        open_cmd: "cursor",
        icon: "cursor.svg",
        always_available: false,
    },
    EditorDefinition {
        id: "windsurf",
        name: "Windsurf",
        detect_cmd: "windsurf",
        open_cmd: "windsurf",
        icon: "windsurf.svg",
        always_available: false,
    },
    EditorDefinition {
        id: "zed",
        name: "Zed",
        detect_cmd: "zed",
        open_cmd: "zed",
        icon: "zed.svg",
        always_available: false,
    },
    EditorDefinition {
        id: "sublime",
        name: "Sublime Text",
        detect_cmd: "subl",
        open_cmd: "subl",
        icon: "sublime.svg",
        always_available: false,
    },
    EditorDefinition {
        id: "vim",
        name: "Vim",
        detect_cmd: "vim",
        open_cmd: "vim",
        icon: "vim.svg",
        always_available: false,
    },
    EditorDefinition {
        id: "neovim",
        name: "Neovim",
        detect_cmd: "nvim",
        open_cmd: "nvim",
        icon: "neovim.svg",
        always_available: false,
    },
    EditorDefinition {
        id: "idea",
        name: "IntelliJ IDEA",
        detect_cmd: "idea",
        open_cmd: "idea",
        icon: "idea.svg",
        always_available: false,
    },
    EditorDefinition {
        id: "pycharm",
        name: "PyCharm",
        detect_cmd: "pycharm",
        open_cmd: "pycharm",
        icon: "pycharm.svg",
        always_available: false,
    },
    EditorDefinition {
        id: "webstorm",
        name: "WebStorm",
        detect_cmd: "webstorm",
        open_cmd: "webstorm",
        icon: "webstorm.svg",
        always_available: false,
    },
    EditorDefinition {
        id: "xcode",
        name: "Xcode",
        detect_cmd: "xcode-select",
        open_cmd: "open -a Xcode",
        icon: "xcode.svg",
        always_available: false,
    },
    EditorDefinition {
        id: "android-studio",
        name: "Android Studio",
        detect_cmd: "studio",
        open_cmd: "studio",
        icon: "android-studio.svg",
        always_available: false,
    },
    EditorDefinition {
        id: "textmate",
        name: "TextMate",
        detect_cmd: "mate",
        open_cmd: "mate",
        icon: "textmate.svg",
        always_available: false,
    },
    EditorDefinition {
        id: "terminal",
        name: "Terminal",
        detect_cmd: "",
        open_cmd: "open -a Terminal",
        icon: "terminal.svg",
        always_available: true,
    },
    EditorDefinition {
        id: "finder",
        name: "Finder",
        detect_cmd: "",
        open_cmd: "open",
        icon: "finder.svg",
        always_available: true,
    },
    EditorDefinition {
        id: "builtin",
        name: "Built-in Editor",
        detect_cmd: "",
        open_cmd: "",
        icon: "builtin.svg",
        always_available: true,
    },
];
